KitapKulubuYeni/KitapKulubu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KitapKulubu.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Hakkımızda";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "iletişim";

            return View();
        }
        public ActionResult Activity()
        {
            ViewBag.Message = "Etkinlikler";

            return View();
        }
        public ActionResult Books()
        {
            ViewBag.Message = "Kitaplar";

            return View();
        }
        public ActionResult Admin()
        {
            ViewBag.Message = "AdminGiris";

            return View();
        }
    }
}

KitapKulubuYeni/KitapKulubu/Controllers/KitaplarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KitapKulubu.Models;

namespace KitapKulubu.Controllers
{
    public class KitaplarController : Controller
    {
        private KitapKulubuEntities db = new KitapKulubuEntities();

        // GET: Kitaplar
        public ActionResult Index()
        {
            return View(db.Kitaplar.ToList());
        }

        // GET: Kitaplar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kitaplar kitaplar = db.Kitaplar.Find(id);
            if (kitaplar == null)
            {
                return HttpNotFound();
            }
            return View(kitaplar);
        }

        // GET: Kitaplar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kitaplar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KitapID,kitapAd,yazar,Kategori,sayfasayisi,yayinevi,icerik,adet,kitapFoto")] Kitaplar kitaplar)
        {
            if (ModelState.IsValid)
            {
                db.Kitaplar.Add(kitaplar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kitaplar);
        }

        // GET: Kitaplar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kitaplar kitaplar = db.Kitaplar.Find(id);
            if (kitaplar == null)
            {
                return HttpNotFound();
            }
            return View(kitaplar);
        }

        // POST: Kitaplar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KitapID,kitapAd,yazar,Kategori,sayfasayisi,yayinevi,icerik,adet,kitapFoto")] Kitaplar kitaplar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kitaplar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kitaplar);
        }

        // GET: Kitaplar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kitaplar kitaplar = db.Kitaplar.Find(id);
            if (kitaplar == null)
            {
                return HttpNotFound();
            }
            return View(kitaplar);
        }

        // POST: Kitaplar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kitaplar kitaplar = db.Kitaplar.Find(id);
            db.Kitaplar.Remove(kitaplar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KitapKulubuYeni/KitapKulubu/Controllers/KullanicilarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KitapKulubu.Models;

namespace KitapKulubu.Controllers
{
    public class KullanicilarController : Controller
    {
        private KitapKulubuEntities db = new KitapKulubuEntities();

        // GET: Kullanicilar
        public ActionResult Index()
        {
            return View(db.Kullanicilar.ToList());
        }

        // GET: Kullanicilar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kullanicilar kullanicilar = db.Kullanicilar.Find(id);
            if (kullanicilar == null)
            {
                return HttpNotFound();
            }
            return View(kullanicilar);
        }

        // GET: Kullanicilar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kullanicilar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KullaniciID,kullaniciAd,kullanıcıSoyad,mailAdres,dogumTar,telefon,kullaniciTur,girisAdı,sifre")] Kullanicilar kullanicilar)
        {
            if (ModelState.IsValid)
            {
                db.Kullanicilar.Add(kullanicilar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kullanicilar);
        }

        // GET: Kullanicilar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kullanicilar kullanicilar = db.Kullanicilar.Find(id);
            if (kullanicilar == null)
            {
                return HttpNotFound();
            }
            return View(kullanicilar);
        }

        // POST: Kullanicilar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KullaniciID,kullaniciAd,kullanıcıSoyad,mailAdres,dogumTar,telefon,kullaniciTur,girisAdı,sifre")] Kullanicilar kullanicilar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kullanicilar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kullanicilar);
        }

        // GET: Kullanicilar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kullanicilar kullanicilar = db.Kullanicilar.Find(id);
            if (kullanicilar == null)
            {
                return HttpNotFound();
            }
            return View(kullanicilar);
        }

        // POST: Kullanicilar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kullanicilar kullanicilar = db.Kullanicilar.Find(id);
            db.Kullanicilar.Remove(kullanicilar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KitapKulubuYeni/KitapKulubu/Views/Home/About.cshtml
@{
    ViewBag.Title = "Hakkımızda";
}
<div class="panel panel-warning">
    <div class="panel-heading">
        <h4>
            <font color="#312D2D">Ben Kimim? Bu Sitenin Amacı Nedir?</font>
        </h4>
    </div>
    <div class="row">
        <div class="col-md-8">
            <p align="center" style="font-size:16px;margin:50px 20px 0 30px">
                
                Öncelikle Merhaba,<br />
                Ben Zeynep Torun. Sakarya Üniversitesi Bilgisayar Mühendisliği öğrencisiyim. Kitap okumaktan ve onları 
                paylaşmaktan hoşlanan, benim gibi hisseden insanlarlarla bir arada olmaktan mutluluk duyan biriyim...
                Kitaplarımı paylaşıp, kitap sevenleri bir araya getirmek için bu kulübü oluşturdum. Kulüp olarak kitap 
                paylaşımlarında bulunup, çeşitli etkinliklerde bir araya geliyoruz, kütüphanemizi çalışmak ve kitap 
                okumak için kullanabiliyoruz.
                    Üyelerimiz kütüphaneye gelip almak istediği kitabın bir başka üye tarafından alınmış 
                olması ve kitabı tekrar almaya gelmek için vakit bulamaması gibi bir duruma karşı, kütüphaneye
                gelmeden almak istedikleri kitabı önceden rezerve edebilmelerini sağlamak amacıyla da bu site hazırlandı.
                Böylece üyelerimiz istediği kitabı kütüphanemizde o anda bulunup bulunmadığına bakabilir, ayırtabilir... 
            </p>
        </div>
        <div class="col-md-4"align="center" >
            <br /><br />
            <img src="~/Content/resimler/ben.jpg"  class="img-circle" style="max-height:250px;max-width:250px;position:center;border:outset"  />
        </div>
    </div>


    <div class="panel-body">
        <p style="max-width:800px">
            <h3> Kütüphane Hakkında</h3>
                Aranan kitap başka bir kullanıcı tarafından ödünç alınmış ise, geri getirildiğinde ödünç alınmak üzere yapılan
            işleme "rezervasyon (Ayırtma)" denir. Kullanıcı sitemiz üzerinden kendi hesabına girer ve katalog tarama yaparak
            istediği kitabı ayırtma işlemini yapabilir. Ayrılan kitaplar kullanıcıya bildirimden itibaren 7 gün içinde alınmazsa
            ayırtma işlemi iptal edilir. Üyeler en fazla 3 kitabı ayırtabilir.

            <h3> Peki Bağış Yapmak İster Misin? </h3>
                Herhangi bir ticari amacı olmayan bir kulubüyüz. Tüm kitaplar ücretsiz olarak sunuluyor. Üyelerimizden gelen
            kitaplarla da büyümeye devam ediyoruz.
            Sitemizdeki tüm içerikler benim tarafımdan yazıldı. Ayrıca sitenin hiç bir yerine reklam koymadım.
            Eğer siz de sunucu, hosting vs masraflarına katkıda bulunmak isterseniz benimle iletişime geçip, kütüphanemize bağış
            yapabilirsiniz.

        </p>
    </div>
</div>

KitapKulubuYeni/KitapKulubu/Views/Home/Activity.cshtml
@{
    ViewBag.Title = "Etkinlikler";
}
    
<div class="row" style="margin-top:40px ">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>Etkinlikler</h4>
            </div>
            <div class="panel-body;col-md-12" style="margin-top:20px">
               
                Etkinlik Tarihi: <input type="datetime-local" name="bdaytime">
                <input type="submit" style="margin-left:10px" value="Gönder">
                
               
                <div style="border-style:dotted;margin-top:10px">
                    <div class="row">
                    <div  class="col-md-4"><img src="~/Content/resimler/resimyok.png" style="margin-left:10px" alt=""></div>
                   <div  class="col-md-8"><br /><h5>etkinlik başlığı</h5></div>

                    </div>
                </div>

                <div style="border-style:dotted;margin-top:10px">
                    <div class="row">
                        <div class="col-md-4"><img src="~/Content/resimler/resimyok.png" style="margin-left:10px" alt=""></div>
                        <div class="col-md-8"><br /><h5>etkinlik başlığı</h5></div>
                    </div>
                </div>

                <div style="border-style:dotted;margin-top:10px">
                    <div class="row">
                        <div class="col-md-4"><img src="~/Content/resimler/resimyok.png" style="margin-left:10px" alt=""></div>
                        <div class="col-md-8"><br /><h5>etkinlik başlığı</h5></div>
                    </div>
                </div>
            </div>
         
            
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
            <h4>Duyurular</h4>
            </div>
            <div class="panel-body" style="height:775px">
                <div class="col-md-12"><br/><br />
                    <a href="http://www.google.com"> duyuru 1</a><br />
                    şlksdkjlkşsfdlkd
                    sdfsadf
                    sadfsadf
                    adsf
                    <a href="http://www.google.com"> duyuru 2</a><br />
                    şlksdkjlkşsfdlkd
                    sdfsadf
                    sadfsadf
                    adsf

                </div>
            </div>
        </div>
    </div>
</div>

KitapKulubuYeni/KitapKulubu/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "ADMİN";
}
@model List<KitapKulubu.Models.Kullanicilar>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Admin Panel</h4>
                </div>
                <div class="panel-body" >
                    <button type="button" class="btn btn-link btn-lg">
                        <span class="glyphicon glyphicon-user"></span> @Html.ActionLink("Profilim", "Index", "Admin")
                    </button>
                    <button type="button" class="btn btn-link btn-lg">
                        <span class="glyphicon glyphicon-education"></span> @Html.ActionLink("Kitap Ayarları", "Index", "Kitaplar")
                    </button>

                    <button type="button" class="btn btn-link btn-lg">
                        <span class="glyphicon glyphicon-sunglasses"></span>@Html.ActionLink("Üye Bilgileri", "Index", "Kullanicilar")
                    </button>
                    <button type="button" class="btn btn-link btn-lg">
                        <span class="glyphicon glyphicon-star"></span> @Html.ActionLink("Etkinlikler", "Index", "Etkinlikler")
                    </button>
                    <button type="button" class="btn btn-link btn-lg">
                        <span class="glyphicon glyphicon-bullhorn"></span>@Html.ActionLink("Duyurular", "Index", "Duyurular")
                    </button>
            </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Kişisel Bilgilerim:</h4>
                </div>
                    <div class="panel-body">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th class="col-lg-2">Ad:</th>
                                    <th class="col-lg-2">Soyad</th>
                                    <th class="col-lg-2">E-Posta:</th>
                                    <th class="col-lg-2">Doğum Tarihi:</th>
                                    <th class="col-lg-2">Telefon:</th>
                                    <th class="col-lg-2">Şifre:</th>

                                    
                                </tr>
                            </thead>
                            <tbody>
                               
                          </tbody>
                        </table>
                    </div>
                </div>
            </div>
    </div>
</div>

KitapKulubuYeni/KitapKulubu/Views/Home/Books.cshtml
@{
    ViewBag.Title = "Kitaplar";
}
<div class="col-md-12">
    <div class="row">
        <div class="panel-body">
            <fieldset style="background-color:lavenderblush">
                <div class="col-md-4">
                    <br />
                    <label class="col-md-4 control-label">Kitap Durumu:</label>
                     <input type="radio" name="gender" value="TumK">Tüm Kitaplar<br>
                    <input type="radio" name="gender" value="REdilen"> Rezerve Edilme<br>
                    <input type="radio" name="gender" value="Redilmeyen"> Rezerve Edilenler<br><br />
                </div>
                <div class="col-md-4">
                    <br />
                    <label class="col-md-4 control-label">Yazar Adı:</label>
                    <input class="col-md-8" type="text" id="yazarAdi">
                    <br /><br />
                    <label class="col-md-4 control-label">Eser Adı:</label>
                    <input class="col-md-8" type="text" id="yazarAdi"><br />
                </div>
                <div class="col-md-4">
                    <br />
                    <label class="col-md-4 control-label">Eser Türü: </label>
                    <select class="col-md-8">
                        <option value="Secim">Bir Seçim Yapın</option>
                        <option value="Tarihi">Tarihi</option>
                        <option value="Bilimsel">Bilimsel</option>
                        <option value="Romantik">Romantik</option>
                        <option value="Fantastik">Fantastik</option>
                    </select><br /><br />
                    <input type="submit" style="margin-left:50px" value="Gönder">
                </div>
            </fieldset>
        </div>
    </div>
    <div class="row">
        <div class="panel-body">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row" style="height:160px;">
                            <div class="col-md-4">
                                <img class="img-responsive" src="~/Content/resimler/turklerınTarihi.png" alt="" />
                            </div>
                            <div class="col-md-8">
                                <h4><a href="etiket">Türklerin Tarihi </a> </h4>
                                <p>İçerik: Koca bir kavmin binlerce kilometreyi üç asır içinde geçtiğini düşünün...</p>
                                Yazar: ilber ortaylı<br />
                                <input type="checkbox" name="vehicle">Rezerve et<br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row" style="height:160px;">
                            <div class="col-md-4">
                                <img class="img-responsive" src="~/Content/resimler/KanadıKırıkKuslar.png" alt="" />
                            </div>
                            <div class="col-md-8">
                                <h4> <a href="etiket">Kanadı Kırık Kuşlar </a> </h4>
                                <p> 1930'ların Almanyası... Nazilerin baskısından bunalan Yahudi asıllı tıp doktoru...</p>
                                Yazar: Ayşe Kulin<br />
                                <input type="checkbox" name="vehicle">Rezerve et<br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row" style="height:160px;">
                            <div class="col-md-4">
                                <img class="img-responsive" src="~/Content/resimler/sevdalinka.png" alt="" />
                            </div>
                            <div class="col-md-8">
                                <h4> <a href="etiket">Sevdalinka </a> </h4>
                                <p> Aynı ırktan, kim bilir belki de aynı soydan geliyorlardı. Aynı yaşlarda, aynı...</p>
                                Yazar: Ayşe Kulin<br />
                                <input type="checkbox" name="vehicle">Rezerve et<br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="panel-body">
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="row" style="height:160px;">
                                    <div class="col-md-4">
                                        <img class="img-responsive" src="~/Content/resimler/turklerınTarihi.png" alt="" />
                                    </div>
                                    <div class="col-md-8">
                                        <h4><a href="etiket">Türklerin Tarihi </a> </h4>
                                        <p>İçerik: Koca bir kavmin binlerce kilometreyi üç asır içinde geçtiğini düşünün...</p>
                                        Yazar: ilber ortaylı<br />
                                        <input type="checkbox" name="vehicle">Rezerve et<br>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="row" style="height:160px;">
                                    <div class="col-md-4">
                                        <img class="img-responsive" src="~/Content/resimler/KanadıKırıkKuslar.png" alt="" />
                                    </div>
                                    <div class="col-md-8">
                                        <h4> <a href="etiket">Kanadı Kırık Kuşlar </a> </h4>
                                        <p> 1930'ların Almanyası... Nazilerin baskısından bunalan Yahudi asıllı tıp doktoru...</p>
                                        Yazar: Ayşe Kulin<br />
                                        <input type="checkbox" name="vehicle">Rezerve et<br>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="row" style="height:160px;">
                                    <div class="col-md-4">
                                        <img class="img-responsive" src="~/Content/resimler/sevdalinka.png" alt="" />
                                    </div>
                                    <div class="col-md-8">
                                        <h4> <a href="etiket">Sevdalinka </a> </h4>
                                        <p> Aynı ırktan, kim bilir belki de aynı soydan geliyorlardı. Aynı yaşlarda, aynı...</p>
                                        Yazar: Ayşe Kulin<br />
                                        <input type="checkbox" name="vehicle">Rezerve et<br>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="panel-body">
                            <div class="col-md-4">
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div class="row" style="height:160px;">
                                            <div class="col-md-4">
                                                <img class="img-responsive" src="~/Content/resimler/turklerınTarihi.png" alt="" />
                                            </div>
                                            <div class="col-md-8">
                                                <h4><a href="etiket">Türklerin Tarihi </a> </h4>
                                                <p>İçerik: Koca bir kavmin binlerce kilometreyi üç asır içinde geçtiğini düşünün...</p>
                                                Yazar: ilber ortaylı<br />
                                                <input type="checkbox" name="vehicle">Rezerve et<br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div class="row" style="height:160px;">
                                            <div class="col-md-4">
                                                <img class="img-responsive" src="~/Content/resimler/KanadıKırıkKuslar.png" alt="" />
                                            </div>
                                            <div class="col-md-8">
                                                <h4> <a href="etiket">Kanadı Kırık Kuşlar </a> </h4>
                                                <p> 1930'ların Almanyası... Nazilerin baskısından bunalan Yahudi asıllı tıp doktoru...</p>
                                                Yazar: Ayşe Kulin<br />
                                                <input type="checkbox" name="vehicle">Rezerve et<br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div class="row" style="height:160px;">
                                            <div class="col-md-4">
                                                <img class="img-responsive" src="~/Content/resimler/sevdalinka.png" alt="" />
                                            </div>
                                            <div class="col-md-8">
                                                <h4> <a href="etiket">Sevdalinka </a> </h4>
                                                <p> Aynı ırktan, kim bilir belki de aynı soydan geliyorlardı. Aynı yaşlarda, aynı...</p>
                                                Yazar: Ayşe Kulin<br />
                                                <input type="checkbox" name="vehicle">Rezerve et<br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

KitapKulubuYeni/KitapKulubu/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Anasayfa";
}
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-body">
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!-- Indicators/ göstergeler -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                        <li data-target="#myCarousel" data-slide-to="3"></li>
                        <li data-target="#myCarousel" data-slide-to="4"></li>
                    </ol>
                    <!-- Wrapper for slides /slider için sarmalayıcı -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="~/Content/resimler/kimlik.png" alt="">
                        </div>
                        <div class="item">
                            <img src="~/Content/resimler/coksatan1.png" alt="">
                        </div>
                        <div class="item">
                            <img src="~/Content/resimler/coksatan2.png" alt="">
                        </div>
                        <div class="item">
                            <img src="~/Content/resimler/coksatan3.png" alt="">
                        </div>
                        <div class="item">
                            <img src="~/Content/resimler/coksatan4.png" alt="">
                        </div>
                    </div>
                    <!-- Controls /sağ ve sol kontroller -->
                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>


    <div class="jumbotron">
        <div class="panel-body">
              <h3>NEDEN BU KULÜP?</h3>
            <h4>
                Kitap kulübü yeri sakarya meydanda olan, Zeynep Torun'a ait kütüphanenin ücretsiz bir şekilde herkese açılmasıyla oluşturulmuş bir kulüptür.
                Bu sitede ise sadece kulüp üyeleri tarafından kullanılmakta olup online kitap rezerve etmelerine yardım etme amacındadır. Üyelerin almak istedikileri kitabın
                kütühanede olup olmaması bilgisini kitabın durumu takip etmesine yardımcı olur.
                Kulüp olarak yazar imza günlerinde ve diğer değişik etkinliklerde biraraya gelip sosyal bir topluluk olma amacındayız.
                Sende bize katıl sosyal bir kitap topluluğunun parçası ol !
            </h4>
            @Html.Partial("_LoginPartial")
        </div>
    </div>

</div>